CC = gcc
CFLAGS = -Wall -Wextra -g


# 请在此处完善 Makefile 文件，补全等号右侧的内容
SRCS = 
OBJS = 
TARGET = matrix_mul

.PHONY: all clean

all: $(TARGET)
# 请在此处完善 Makefile 文件，编写Makefile的规则



# 不要修改下面的代码
clean:
	rm -f $(OBJS) $(TARGET)